name: 'Python platform independent package action'
description: 'Create platform independent Python distribution packages with wheel, FPM and dh-virtualenv support'
branding:
  icon: 'package'
  color: 'white'

inputs:
  install-packaging-tools:
    description: 'Should install packaging tools?'
    required: false
    default: 'true'
  add-wheel-dist:
    description: 'Should create wheel distribution?'
    required: false
    default: 'true'
  debian-dist-type:
    description: 'Debian distribution type (fpm-deb / dh-virtualenv / none)'
    required: false
    default: 'none'
  debian-dist-command:
    description: 'Debian packaging custom command'
    required: false

  python-version:
    description: 'Python version'
    required: false
    default: '3.9'

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install wheel
        mkdir -p dist
    - if: ${{ inputs.install-packaging-tools == 'true' }}
      name: Install packaging tools
      shell: bash
      run: |
        git clone https://github.com/EffectiveRange/packaging-tools.git /tmp/packaging-tools
        sudo bash /tmp/packaging-tools/python/install.sh
        pip install stdeb
    - if: ${{ inputs.add-wheel-dist == 'true' }}
      name: Create wheel distribution
      shell: bash
      run: pack_python . -s wheel
    - if: ${{ inputs.debian-dist-type == 'fpm-deb' }}
      name: Create debian distribution (fpm-deb)
      shell: bash
      run: pack_python . -s fpm-deb
    - if: ${{ inputs.debian-dist-type == 'dh-virtualenv' }}
      name: Create debian distribution (dh-virtualenv)
      shell: bash
      run: pack_python . -s dh-virtualenv
    - if: ${{ inputs.debian-dist-command }}
      name: Create debian distribution (custom)
      shell: bash
      run: eval ${{ inputs.debian-dist-command }}
