name: 'Python platform independent package action'
description: 'Create platform independent Python distribution packages with wheel, FPM and dh-virtualenv support'
branding:
  icon: 'package'
  color: 'white'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.9'
  add-wheel-dist:
    description: 'Should create wheel distribution?'
    required: false
    default: 'true'
  debian-dist-type:
    description: 'Debian distribution type (fpm-deb / dh-virtualenv / none)'
    required: false
    default: 'none'
  debian-dist-command:
    description: 'Debian build command'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .
        mkdir -p dist
    - if: ${{ inputs.add-wheel-dist == 'true' }}
      name: Create wheel distribution
      shell: bash
      run: |
        pip install wheel
        pack_python . -s wheel
    - if: ${{ inputs.debian-dist-type == 'fpm-deb' }}
      name: Create debian distribution (fpm-deb)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential
        sudo gem install -N fpm
        
        COMMAND="${{ inputs.debian-dist-command }}"
        
        # Default FPM command
        COMMAND=${COMMAND:-"pack_python . -s fpm-deb"}
        
        eval $COMMAND
    - if: ${{ inputs.debian-dist-type == 'dh-virtualenv' }}
      name: Create debian distribution (dh-virtualenv)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper devscripts equivs dh-virtualenv python3-virtualenv python3-all dh-python
        pip install stdeb
        
        COMMAND="${{ inputs.debian-dist-command }}"
        
        # Default dh-virtualenv command
        COMMAND=${COMMAND:-"pack_python . -s dh-virtualenv"}
        
        eval $COMMAND
        
        # Copy debian package to dist folder if generated out of tree
        cp ../*.deb dist || true
