name: Test Python packaging with devcontainer

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-devcontainer-arm32v7:
    name: Test creating arm32v7 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packaging tools
        run: |
          git clone https://github.com/EffectiveRange/packaging-tools.git /tmp/packaging-tools
          sudo bash /tmp/packaging-tools/python/install.sh
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./devcontainer
        with:
          container-platform: 'linux/arm/v7'
          container-config: 'arm32v7'
          debian-dist-type: 'fpm-deb'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/python3-test-module_1.0.0_all.deb

  test-devcontainer-arm64v8:
    name: Test creating arm64v8 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packaging tools
        run: |
          git clone https://github.com/EffectiveRange/packaging-tools.git /tmp/packaging-tools
          sudo bash /tmp/packaging-tools/python/install.sh
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./devcontainer
        with:
          container-platform: 'linux/arm64'
          container-config: 'arm64v8'
          debian-dist-type: 'dh-virtualenv'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/test-module_1.0.0-1_all.deb

  test-devcontainer-amd64:
    name: Test creating amd64 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packaging tools
        run: |
          git clone https://github.com/EffectiveRange/packaging-tools.git /tmp/packaging-tools
          sudo bash /tmp/packaging-tools/python/install.sh
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./devcontainer
        with:
          add-wheel-dist: 'false'
          debian-dist-command: 'pack_python . --all'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/python3-test-module_1.0.0_all.deb
          ls dist/test-module_1.0.0-1_all.deb
