name: Test platform independent Python packaging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-native-fpm-deb-default-command:
    name: Test creating native fpm-deb packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./native
        with:
          debian-dist-type: 'fpm-deb'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/python3-test-module_1.0.0_all.deb

  test-native-fpm-deb-custom-command:
    name: Test creating native fpm-deb packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./native
        with:
          debian-dist-type: 'fpm-deb'
          debian-dist-command: 'fpm -s python -t deb --package dist --force --log warn setup.py'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/python-test-module_1.0.0_all.deb

  test-native-dh-virtualenv-default-command:
    name: Test creating native dh-virtualenv packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./native
        with:
          debian-dist-type: 'dh-virtualenv'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/test-module_1.0.0-1_all.deb

  test-native-dh-virtualenv-custom-command:
    name: Test creating native dh-virtualenv packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./native
        with:
          debian-dist-type: 'dh-virtualenv'
          debian-dist-command: 'dpkg-buildpackage -us -ui -uc -tc'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/test-module_1.0.0_amd64.deb
