name: Test Python packaging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-main-native-fpm-deb:
    name: Test creating native packages (fpm-deb)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./
        with:
          package-version: '1.1.0'
          debian-dist-type: 'fpm-deb'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.1.0.tar.gz
          ls dist/test_module-1.1.0-py3-none-any.whl
          ls dist/python3-test-module_1.1.0_all.deb

  test-main-dh-native-virtualenv:
    name: Test creating native packages (dh-virtualenv)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./
        with:
          package-version: '1.1.0'
          debian-dist-type: 'dh-virtualenv'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.1.0.tar.gz
          ls dist/test_module-1.1.0-py3-none-any.whl
          ls dist/test-module_1.1.0-1_all.deb

  test-main-devcontainer-fpm-deb:
    name: Test creating packages in devcontainer (fpm-deb)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./
        with:
          package-version: '1.1.0'
          use-devcontainer: 'true'
          container-platform: 'linux/arm64'
          container-config: 'arm64v8'
          debian-dist-type: 'fpm-deb'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.1.0.tar.gz
          ls dist/test_module-1.1.0-py3-none-any.whl
          ls dist/python3-test-module_1.1.0_all.deb

  test-main-devcontainer-dh-virtualenv:
    name: Test creating packages in devcontainer (dh-virtualenv)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./
        with:
          package-version: '1.1.0'
          use-devcontainer: 'true'
          debian-dist-type: 'dh-virtualenv'

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test-module-1.1.0.tar.gz
          ls dist/test_module-1.1.0-py3-none-any.whl
          ls dist/test-module_1.1.0-1_all.deb
