name: Test Python packaging with devcontainer

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-devcontainer-arm32v7:
    name: Test creating arm32v7 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./devcontainer
        with:
          container-platform: 'linux/arm/v7'
          container-config: 'arm32v7'
          packaging-command: python3 setup.py sdist bdist_wheel

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test_module-1.0.0-py3-none-any.whl

  test-devcontainer-arm64v8:
    name: Test creating arm64v8 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./devcontainer
        with:
          container-platform: 'linux/arm64'
          container-config: 'arm64v8'
          packaging-command: python3 setup.py sdist bdist_wheel

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test_module-1.0.0-py3-none-any.whl

  test-devcontainer-amd64:
    name: Test creating amd64 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: |
          cp -a test/. .
          rm -rf dist

      - name: Create packages
        uses: ./devcontainer
        with:
          packaging-command: python3 setup.py sdist bdist_wheel

      - name: Assert packages have created
        run: |
          set -e
          ls -l dist
          ls dist/test_module-1.0.0-py3-none-any.whl
